### ISSUE TITLE
Task descriptions with long word cause layout breaks in dashboard widget

### ISSUE THREAD

**Issue by MichelleBlanchette** [PurpleTurtleCreative/completionist#65]
Long word like a link URL, see screenshot below.

Confirmed fix is to add `word-break` style rule:
```css
.ptc-TaskRow .body .description {
  white-space: pre-wrap;
  margin-top: 0.7em;
  color: #334e68;
  word-break: break-word; <-- Add this
}
```

![Screen Shot 2022-03-06 at 9 21 09 AM](https://user-images.githubusercontent.com/33374343/156927271-5191744b-0942-407d-871b-2d929f1a4954.png)
